
site_name: Bioinformatics Documentation

repo_name: melbournebioinformatics/MelBioInf_docs
repo_url: https://github.com/melbournebioinformatics/MelBioInf_docs

# Comment below - old universal analytics tracking. No longer used.
# google_analytics: ['UA-21794901-5', 'www.melbournebioinformatics.org.au/tutorials/']

# needs pip install mkdocs-material
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate

#theme_dir: 'material-theme-overrides'  # needs updating for mkdocs 0.17

extra_css:
  - 'extra.css'


copyright: <a href="https://www.melbournebioinformatics.org.au/">Melbourne Bioinformatics</a>

nav:
    - Home: 'index.md'
    - 'Tools and skill development':
        - 'What is Bioinformatics?': 'guides/bioinfo.md'
        - 'Introduction to the Galaxy Platform': 'guides/galaxy.md'
        - 'Introduction to Galaxy Workflows': 'tutorials/galaxy-workflows/galaxy-workflows.md'
        - 'Introduction to Python': 'tutorials/python_overview/python_overview.md'
        - 'Introduction to Unix': 'tutorials/unix/unix.md'
        - 'Introduction to R for Biologists': 'tutorials/intro_R_biologists/intro_R_biologists.md'
        - 'Introduction to Genome Browsers': 'tutorials/Genome_browsers/GenomeBrowsers_Intro.md'
        - 'Introduction to CWL': 'tutorials/cwl_2022/cwl_2022.md'
        - 'RNA-seq Experimental Design': 'tutorials/rna_seq_exp_design/rna_seq_experimental_design.md'
        - 'Containerized Bioinformatics': 'tutorials/docker/docker.md'
        - 'Command-line software development': 'tutorials/bionitio/bionitio.md'
        - 'Version Control with Git': 'tutorials/git/git.md'
        - 'Workflow Translation With Janis': 'tutorials/janis_translate/janis_translate.md'
    - 'Genomics':
        - 'Variant detection':
            - 'Introduction to Variant detection': 'tutorials/var_detect_advanced/var_detect_advanced_background.md'
            - 'Variant Calling part 1 (Galaxy)': 'tutorials/variant_calling_galaxy_1/variant_calling_galaxy_1.md'
            - 'Variant Calling part 2 (Galaxy)': 'tutorials/var_detect_advanced/var_detect_advanced.md'
            - 'Long-read Structural Variant Calling': 'tutorials/longread_sv_calling/longread_sv_calling.md'
            - 'Variant calling using command-line tools': 'tutorials/variant_calling_gatk1/variant_calling_gatk1.md'
        - 'de novo assembly':
            - 'Introduction to de novo assembly with Velvet': 'tutorials/assembly/assembly-background.md'
            - 'Introduction to de novo genome assembly for Illumina reads': 'tutorials/assembly/assembly-protocol.md'
            - 'de novo assembly of Illumina reads using Velvet (Galaxy)': 'tutorials/assembly/assembly.md'
            - 'de novo assembly of Illumina reads using Spades (Galaxy)': 'tutorials/assembly/spades.md'
            - 'de novo assembly of PacBio reads (unix)': 'tutorials/pacbio/index.md'
            - 'Hybrid genome assembly - Nanopore and Illumina': 'tutorials/hybrid_assembly/nanopore_assembly.md'
        - 'Metabarcoding':
            - 'Intro to Metabarcoding using QIIME2: *Marine dataset*': 'tutorials/qiime2/qiime2.md'
            - 'Intro to Metabarcoding using QIIME2: *Mammal dataset*': 'tutorials/qiime2_mammal/qiime2_mammal.md'
    - 'Transcriptomics':
        - 'RNAseq Experimental Design': 'tutorials/rna_seq_exp_design/rna_seq_experimental_design.md'
        - 'Bulk RNAseq':
            - 'Introduction to bulk RNAseq analysis': 'tutorials/rna_seq_dge_basic/rna_seq_basic_background.md'
            - 'RNAseq analysis using HISAT2 (Galaxy)': 'tutorials/rna_seq_dge_basic/rna_seq_basic_tutorial.md'
            - 'RNAseq analysis using Tuxedo (Galaxy)': 'tutorials/rna_seq_dge_basic/rna_seq_basic_tuxedo.md'
            - 'RNAseq differential expression tool comparision (Galaxy)': 'tutorials/rna_seq_dge_advanced/rna_seq_advanced_tutorial.md'
            - 'RNAseq differential expression in R': 'tutorials/rna_seq_dge_in_r/rna_seq_r.md'
        - 'Singlecell RNAseq':
            - '10X single-cell RNA-seq analysis in R': 'tutorials/singlecell/index.md'
    - 'Proteomics':
        - 'Identifying proteins from mass spectrometry data': 'tutorials/proteomics_basic/proteomics_basic.md'
    - 'Statistics and Visualisation':
        - 'Data visualisation with Python': 'tutorials/python_viz/python_viz.md'
    - 'Structural Modelling':
        - 'Molecular Dynamics - Introduction to cluster computing': 'tutorials/molecular_dynamics_101/molecular_dynamics_101.md'
        - 'Molecular Dynamics - Building input files, visualising the trajectory': 'tutorials/molecular_dynamics_201/molecular_dynamics_201.md'
    - 'Workshop Delivery Mode Information':
        - 'Workshops on Nectar Instances': 'tutorials/workshop_delivery_mode_info/workshops_nectar.md'
    - 'Archive':
        - 'Introduction to Unix-Archive': 'tutorials/unix_archive_2022/unix.md'
        - 'Introduction to CWL': 'tutorials/cwl/cwl.md'
        - 'Introduction to Git and Github (deprecated)': 'tutorials/using_git/Using_Git.md'

extra_templates: [
  'tutorials/hpc/slides.html',
]
markdown_extensions:
  - 'markdown_include.include'
  - 'markdown.extensions.fenced_code'
  - admonition
  - smarty
  - tables
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown.extensions.attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - sane_lists