site_name: LSCC Documentation
theme: flatly
pages:
- 'Home': 'index.md'
- 'Tutorials':
  - 'Overview': 'tutorials/index.md'
  - 'NGS Overview': 'tutorials/ngs_overview/NGS_Overview.md'
  - 'Using Git and Github for revision control': 'tutorials/using_git/Using_Git.md'
  - 'Variant Detection Advanced': 'tutorials/var_detect_advanced/var_detect_advanced_background.md'
  - 'RNA Seq Basic': 'tutorials/rna_seq_dge_basic/rna_seq_basic_background.md'
  - 'RNA Seq Experimental Design': 'tutorials/rna_seq_exp_design/rna_seq_experimental_design.md'
  - 'Introduction to HPC': 'tutorials/hpc/index.md'
  - 'Introduction to Unix': 'tutorials/unix/index.md'
  - 'Python Overview': 'tutorials/python_overview/python_overview.md'
  - 'Microbial de novo Assembly for Illumina Data': 'tutorials/assembly/assembly.md'
extra_templates: [
  'tutorials/hpc/slides.html',
  'tutorials/unix/slides.html',
]
markdown_extensions: [
  'markdown_include.include',
  'showable',
  'markdown.extensions.fenced_code',
]
